# Generated by Django 3.0.4 on 2020-04-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detailed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=100)),
                ('positive', models.FloatField(default=0)),
                ('negative', models.FloatField(default=0)),
                ('dorm', models.PositiveIntegerField(default=0)),
                ('countofdorm', models.PositiveIntegerField(default=0)),
                ('tweetcount', models.IntegerField(default=1000)),
                ('time1', models.PositiveIntegerField(default=0)),
                ('poswc', models.CharField(default='', max_length=10000000)),
                ('negwc', models.CharField(default='', max_length=10000000)),
            ],
        ),
        migrations.CreateModel(
            name='Searchres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=100)),
                ('positive', models.FloatField(default=0)),
                ('negative', models.FloatField(default=0)),
                ('postweet1', models.CharField(default='', max_length=1000)),
                ('postweet2', models.CharField(default='', max_length=1000)),
                ('negtweet1', models.CharField(default='', max_length=1000)),
                ('negtweet2', models.CharField(default='', max_length=1000)),
                ('tweetcount', models.IntegerField(default=1000)),
                ('time1', models.PositiveIntegerField(default=0)),
                ('poswc', models.CharField(default='', max_length=10000000)),
                ('negwc', models.CharField(default='', max_length=10000000)),
            ],
        ),
    ]
